services:
  uv:
    build: 
      context: .
      dockerfile: Dockerfile
    shm_size: '8gb'
    ports:
      - "8888:8888"
    volumes:
      - .:/usr/local/app
    working_dir: /usr/local/app
    environment:
      - PATH=/root/.cargo/bin:${PATH}
      - "NVIDIA_VISIBLE_DEVICES=all"
      - "NVIDIA_DRIVER_CAPABILITIES=all"
    command: ["tail", "-f", "/dev/null"]
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['0']
            capabilities: [gpu]