services:
  uv:
    build: 
      context: .
      dockerfile: Dockerfile
    shm_size: '8gb'
    ports:
      - "8888:8888"
    volumes:
      - .:/app
    #GPUを使う場合の設定
    environment:
      - "NVIDIA_VISIBLE_DEVICES=all"
      - "NVIDIA_DRIVER_CAPABILITIES=all"
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['0']
            capabilities: [gpu]