[project]
name = "torch-env"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "jupyter>=1.1.1",
    "numpy>=2.1.3",
    "torch>=2.5.1",
    "torchvision>=0.20.1",
]
